@host = http://127.0.0.1:8080
@endpoint = users
@idUser = 637bf7efd598b8e0cf88ee61
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiZjdlZmQ1OThiOGUwY2Y4OGVlNjEiLCJpYXQiOjE2NjkyMjQ0OTIsImV4cCI6MTY2OTIyNDc5Mn0.STfqNfSTdtbbxH9hIPW812Y8TFPTKyGIEzAt9VRkX1c

### Get all users
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json
Authorization: bearer {{token}}

### Get user by ID
GET {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

### Create user
Post {{host}}/{{endpoint}}
Content-Type: application/json

{
    "name" : "User2",
    "lastNameF" : "Ledesma",
    "lastNameM" : "Soto",
    "email" : "user2@gmail.com",
    "password" : "123456"
}


### Update user
PUT {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name" : "Rafael update"
}

### Delete user
DELETE {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

