# @host = http://127.0.0.1:8080
@host = https://5ysrhjk7yhwuyftpv35nrib5qu0elkoq.lambda-url.us-east-1.on.aws
@endpoint = users
@idUser = 637bf7efd598b8e0cf88ee61
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiZjdlZmQ1OThiOGUwY2Y4OGVlNjEiLCJpYXQiOjE2NjkyMjkzNDUsImV4cCI6MTY2OTIyOTY0NX0.ydle-SdfRDUPbegJV9LCX_zrb7dQL2CEF1BuqoBdt3A

### Get all users
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json
Authorization: bearer {{token}}

### Get user by ID
GET {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

### Create user
Post {{host}}/{{endpoint}}
Content-Type: application/json

{
    "name" : "User3",
    "lastNameF" : "Ledesma",
    "lastNameM" : "Soto",
    "email" : "user3@gmail.com",
    "password" : "123456"
}


### Update user
PUT {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name" : "Rafael update"
}

### Delete user
DELETE {{host}}/{{endpoint}}/{{idUser}}
Content-Type: application/json
Authorization: bearer {{token}}

