@host = http://127.0.0.1:8080
@endpoint = users


### Get all users
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json


### Create user
Post {{host}}/{{endpoint}}
Content-Type: application/json

{
    "name" : "Rafael",
    "lastNameF" : "Ledesma",
    "lastNameM" : "Soto",
    "email" : "rafael@gmail.com",
    "password" : "123456"
}


