# @host = http://127.0.0.1:8080
@host = https://cva4zfuun6hocdhy5b34xwniam0wmhqe.lambda-url.us-east-1.on.aws
@endpoint = boardroom
@idBoardroom = 637d2f410ffa94a330d85fc5
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdiZjdlZmQ1OThiOGUwY2Y4OGVlNjEiLCJpYXQiOjE2NjkyMzUzNTgsImV4cCI6MTY2OTIzNTY1OH0.XymXFR3OFpqpCd2CdEgtAB9evH-R6yxok69cMFKkIY4


### Get all boardroom
GET {{host}}/{{endpoint}}?limit=5&offset=0
Content-Type: application/json
Authorization: bearer {{token}}

### Get boardroom by ID
GET {{host}}/{{endpoint}}/{{idBoardroom}}
Content-Type: application/json
Authorization: bearer {{token}}

### Create boardroom
Post {{host}}/{{endpoint}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "name" : "Sala 1",
    "imageUrl" : "https://smartup.com.mx/wp-content/uploads/2020/09/Sala-de-Juntas-Angel%C3%B3polis-Smart-Up-e1599512142776.jpg",
    "description" : "Sala de juntas con 14 sillas y pantalla de 70 pulgadas"
}


### Update boardroom
PUT {{host}}/{{endpoint}}/{{idBoardroom}}
Content-Type: application/json
Authorization: bearer {{token}}

{
    "description" : "Sala de juntas con 14 sillas y pantalla de 70 pulgadas"
}

### Delete boardroom
DELETE {{host}}/{{endpoint}}/{{idBoardroom}}
Content-Type: application/json
Authorization: bearer {{token}}
